name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - 'Docs/**'
      - 'README.md'

env:
  BUILD_PACKAGES: 'true'

jobs:

  build:

    runs-on: windows-latest
    
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - uses: actions/checkout@v2

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1

    - name: Authenticate nuget
      run: |
         nuget sources remove -name "github" -configFile nuget.config
         nuget sources add -name "github" -source https://nuget.pkg.github.com/hpa-cognizant/index.json -username ${{ secrets.NUGET_USER }} -password ${{ secrets.NUGET_TOKEN }} -StorePasswordInClearText -configFile nuget.config

    - name: Fetch all tags and branches
      if: ${{ success() && ( env.BUILD_PACKAGES == 'true' || endsWith( github.ref, 'master') ) }}
      run: |
        git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch --prune --unshallow

    - name: Restore Packages
      run: nuget restore ZstdNet.sln
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
    - name: Create NuGet Packages
      if: ${{ success() && ( env.BUILD_PACKAGES == 'true' || endsWith( github.ref, 'master') ) }}
      run: |
        nuget pack ZstdNet/ZstdNet.csproj -Prop Configuration=Release

    - name: Push NuGet packages
      if: ${{ success() && ( env.BUILD_PACKAGES == 'true' || endsWith( github.ref, 'master') ) }}
      run: nuget push *.nupkg -SkipDuplicate -Source "github"


