name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - 'Docs/**'
      - 'README.md'

env:
  BUILD_PACKAGES: 'true'

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - uses: actions/checkout@v2

    - name: Authenticate nuget
      run: |
         dotnet nuget sources remove -name "github" -configFile nuget.config
         dotnet nuget sources add -name "github" -source https://nuget.pkg.github.com/hpa-cognizant/index.json -username ${{ secrets.NUGET_USER }} -password ${{ secrets.NUGET_TOKEN }} -StorePasswordInClearText -configFile nuget.config

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test **/*.Test.csproj

    - name: Push NuGet packages
      if: ${{ success() && ( env.BUILD_PACKAGES == 'true' || endsWith( github.ref, 'master') ) }}
      run: dotnet push ZstdNet/bin/Release/*.nupkg -SkipDuplicate -Source "github"
