name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - 'Docs/**'
      - 'README.md'

env:
  BUILD_PACKAGES: 'true'

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1

    - name: Authenticate nuget
      run: dotnet nuget update source github  --source https://nuget.pkg.github.com/hpa-cognizant/index.json --username ${{ secrets.HPA_NUGET_USER }} --password ${{ secrets.HPA_NUGET_TOKEN }} --store-password-in-clear-text --configfile nuget.config

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release

    - name: Push NuGet packages
      if: ${{ success() && ( env.BUILD_PACKAGES == 'true' || endsWith( github.ref, 'master') ) }}
      run: dotnet nuget push **/*.nupkg --skip-duplicate --source github
